### ISSUE TITLE
Are there any cases where Dicovery.probe can fail except network error?

### ISSUE THREAD

**Issue by komalpharate** [agsh/onvif#100]
Is there any issue if the camera device and the machine never communicated ?
Will onvif module still find its configurations?
Are there any cases where this Dicovery can fail?

**Comment by RogerHardiman** [comment]
discovery uses UDP broadcast packets. In a poor network with packet loss discovery could fail and then the onvif module would not find the camera. Most commercial systems send out the discovery packet multiple times to overcome this.

Discovery is a broadcast packet so it only works over your broadcast domain - ie the IP Addresses that are in the same subnet range as the onvif module.
Broadcast does not normally pass through routers and into other IP address ranges.

Broadcast is used just to help you find the camera's IP address

After that ONVIF uses TCP connections to the camera's IP address for SOAP/XML messages so broadcast is not critical.
