### ISSUE TITLE
Module `http` does not exist in the Haste module map

### ISSUE THREAD

**Issue by divyangsolanki** [agsh/onvif#107]
I am trying to implement "Onvif" in React Native but when i try to discover NVT devices i got this error.

**Error**:
 Error: Unable to resolve module "http" from "/node_modules/onvif/lib/cam.js": Module `http` does not exist in the Haste module map

Here is my **Code**:

import React, { Component } from 'react';
import { Text, View } from 'react-native';
const onvif = require('./node_modules/onvif/lib/onvif');

export default class App extends Component {
  componentWillMount() {
    onvif.Discovery.on('device', (cam, rinfo, xml) => {
        // function will be called as soon as NVT responses
        console.log('Reply from ' + rinfo.address);
        console.log(cam.hostname + ':' + cam.port + cam.path);
    });
    onvif.Discovery.probe();
  }
  render() {
    return null;
  }
}

**Package.json:**
{
  "name": "Onvifexample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "eslint-config-rallycoding": "^3.2.0",
    "onvif": "^0.6.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "xml2js": "*"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-preset-react-native": "4.0.1",
    "jest": "23.6.0",
    "react-test-renderer": "16.3.1",
    "coffeescript": "^1.9.3",
    "coveralls": ">=2.11.2",
    "dot": "^1.0.3",
    "istanbul": ">=0.3.5",
    "jscs": "^1.13.1",
    "jsdoc": "^3.3.0",
    "jshint": "^2.7.0",
    "keypress": "^0.2.1",
    "mocha": ">=2.1.0",
    "mocha-lcov-reporter": "0.0.1",
    "nimble": "^0.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Plsease help to find the solution.**

**Comment by chriswiggins** [comment]
Closing old inactive issue
