### ISSUE TITLE
Failed to login, try to remove onvif beta6 and reinstall but failed to remove

### ISSUE THREAD

**Issue by soovui** [agsh/onvif#112]
Anyone, 

how to remove completely onvif beta6 because I failed to remove.  At 1st everything works fine anc can easily login but after several attempt cannot login anymore even i deleted and recreated the IP address and port and username and password.  This is  what I get disconnected.  But my username and password never change and i successfully login thru my web browser using the same username and password.   Please help and thanks a lot.

6/26/2019, 3:33:03 AMnode: 1930696f.eb3e07
msg : error
"Error: ONVIF SOAP Fault: Sender not Authorized. Invalid username or password! You still have 26 attempt(s)."

**Comment by chriswiggins** [comment]
What camera are you using?

Lots of cameras these days have separate user accounts for ONVIF. This would be the first thing to check

**Comment by chriswiggins** [comment]
Closing after inactivity
