### ISSUE TITLE
getVideoEncoderConfigurationOptions does not follow the specs

### ISSUE THREAD

**Issue by bl0ggy** [agsh/onvif#113]
As stated in [ONVIF-Media-Service-Spec.pdf](https://www.onvif.org/specs/srv/media/ONVIF-Media-Service-Spec.pdf) chapter 5.5.4 :

> If a configuration token is provided, the device shall return the options compatible with that
configuration. If a media profile token is specified, the device shall return the options
compatible with that media profile. If both a media profile token and a configuration token are
specified, the device shall return the options compatible with both that media profile and that
configuration. If no tokens are specified, the options shall be considered generic for the
device.

the token should be optional, not forced like in `Cam.prototype.getVideoEncoderConfigurationOptions` in `media.js` (line 287 at the moment I write this issue)  :

```
if (this.videoEncoderConfigurations && this.videoEncoderConfigurations[0]) {
    token = this.videoEncoderConfigurations[0].$.token;
} else {
    return callback(new Error('No video encoder configuration token is present!'));
}
```

So there are currently 3 issues here :

1. We cannot get generic video encoder configuration options (which is a list of all supported options)
2. We cannot get video encoder configurations options with a media profile token
3. People expecting to receive generic video encore configuration options by omitting the token right after a connection will get back an error as `this` does not have `videoEncoderConfigurations` before we call `getVideoEncoderConfigurations` function

EDIT: the specifications link was for v1706 (Jun 2017), I updated it to the latest one, which has the same specifications for this issue.
EDIT2: the specifications link was for Media2, which is different from Media, but the specifications are still the same for this issue.

**Comment by bl0ggy** [comment]
I just forked your repo and committed a fix.
Would you mind checking if that's correct for you ?
I have not created/updated any test as I do not know how coffee works.

**Comment by agsh** [comment]
Hi, I've looked at your commit, it seems fine. You can make a pull request to see linter errors.
Sorry, I don't have much time to write the tests. Also I haven't got any device to test. So I think, it is normal not to write the tests for now, or to rewrite it in js sometime. Nobody loves coffeescript now)

**Comment by bl0ggy** [comment]
May I know, are you alerted when I add a new commit or post a comment on the pull request ?
In case you are not, I pushed 2 more commits about tests and posted one comment because I don't know what causes the fail on travis and how to debug it :/

**Comment by chriswiggins** [comment]
Closing this in favour of the pull request
