### ISSUE TITLE
Access Channel and Quality

### ISSUE THREAD

**Issue by abdkaviani** [agsh/onvif#117]
Hello

My all devices support Onvif,
I ran this project without any problems in my IP Camera

The question is
My IP & Analog cameras are connected to XVR device, Can I access one of XVR **channel** through XVR ip address?
Or
Can I use rtsp url instead of http in this project?

Another question is:
My devices have two streaming quality (main & extra). Can I choose lower quality?

Thanks a lot

**Comment by chriswiggins** [comment]
Hi @abdkaviani,

You need to use the XVR's and device's different profileTokens to access the different channels / streaming qualities. You can pass these in to the `getStreamUri` function:

`this.getStreamUri({profileToken: 'Profile1'}, callback)`

You can get the different profiles by doing:
`this.getProfiles(function(err, profiles){
    console.log(profiles);
})`
