### ISSUE TITLE
Need help with firewall configuration

### ISSUE THREAD

**Issue by boonya** [agsh/onvif#118]
Hello there.
I just need help to configure my firewall properly.

Currently it is configured as shown below:

```
$ sudo ufw status

Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere
80/tcp                     ALLOW       Anywhere
443/tcp                    ALLOW       Anywhere
1883                       ALLOW       Anywhere
22/tcp (v6)                ALLOW       Anywhere (v6)
80/tcp (v6)                ALLOW       Anywhere (v6)
443/tcp (v6)               ALLOW       Anywhere (v6)
1883 (v6)                  ALLOW       Anywhere (v6)
```

but, when I run `Discovery.probe` on this server it can't find any cams. If I deactivate my firewall this feature works fine. So, I realized that this is something related to UFW service.

I tried to investigate source code a little bit and found that it broadcast some SOAP envelope trough UDP and as far as I understand transmitters (cameras) should answer on this message with something to the server. But what the access point? I mean port.
Please, help me.

**Comment by chriswiggins** [comment]
Hi @boonya,

You need to allow packets from any UDP port inbound on IPv4 / IPv6

When the discovery module sends the probe packets out, it randomly chooses a port to bind itself on and then the cameras reply to the module on this port

Try the above configuration and let me know how you get on

**Comment by boonya** [comment]
Hello, @chriswiggins 
Thank you. I realized that command `sudo ufw allow proto udp from 192.168.1.0/24` helped me. Where `192.168.1.0/24` is subnetwork where my discoverable cameras placed on.

So, think we can close this issue out.
