### ISSUE TITLE
Can we set the properties received from getVideoSources method

### ISSUE THREAD

**Issue by PrakharPatidar** [agsh/onvif#130]
Hello,

Very useful library. One question though: -

Is it possible to set the properties like brightness, sharpness, backlightCompensation etc of the camera with this module. These properties can be received with getVideoSources method. But didn't set any method to set the properties. If can't be done with this package any lead towards achieving this?

Thanks in advance!

**Comment by RogerHardiman** [comment]
The library supports the ONVIF 'setImageSettings' method.
You'll find the source code around line 65 in the file lib/image.js

https://github.com/agsh/onvif/blob/d6db155383496218656176ea6417034c57be9e16/lib/imaging.js#L65
