### ISSUE TITLE
Does this library support two-way communication through RTSP backchannel?

### ISSUE THREAD

**Issue by tclayson** [agsh/onvif#145]
Is there any way to use this library to send an audio stream back to an ONVIF camera for bidirectional communications? i.e. to create an intercom

Many thanks
Thomas

**Comment by RogerHardiman** [comment]
Funnily enough Iwas debugging a backchannel issue between Axis and IndigoVision as you were posting using Wireshark.

The answer is no, this library only does the ONVIF commands. It does not include anything at the RTSP level which is how the video and audio get transferred between camera and viewer.

Just to clarify, ONVIF commands are things like "Hey camera, what is your make and model" and "Hey cameras, can you zoom and Pan to the left please" and "Hey camera, what is the RTSP URL so I can stream the video and 2 way audio using my favourite RTSP software [like ffmpeg or VLC]"

**Comment by RogerHardiman** [comment]
Just to add to the last post, FFMPEG (replay) and VLC will both stream the video and audio from the camera. But actually I have no idea if any of those support back channel.

**Comment by tclayson** [comment]
Awesome, thanks for your reply. I appreciate it.

So the backchannel is a function of RTSP, rather than ONVIF? I will look into that further.

Many thanks
Thomas

**Comment by RogerHardiman** [comment]
I've not had any time to look at the back channel other than reading that gstreamer as some support for it.
So I'm going to close the issue with a "it is not supported".
But if you find a way to use it, please let us know. Although it is at the RTSP layer (ie below the ONVIF layer) it would be good to add it to the README
