### ISSUE TITLE
Setting system date and time

### ISSUE THREAD

**Issue by Dermiste** [agsh/onvif#15]
Hello there,

Awesome work ! Very helpful :)

Could it be possible to add a method to set system's date and time ?

**Comment by agsh** [comment]
Ok.

**Comment by EastL** [comment]
Hello ~ Are you start to add set system's time ?
I add the setSystemDateAndTime here
https://github.com/EastL/onvif/commit/d8d30f6b601c406463b886021351579d298cdd3a

If you're not start to write this, maybe I could send the pull request?

**Comment by BlueT** [comment]
Hi @EastL I think you can just send the pull request and let @agsh decide to merge or not. :-)
:+1:

**Comment by Dermiste** [comment]
If someone has a working method that's perfect, I am doing research work at
this moment and not too much time to take on SOAP implementation as I never
did it before ...
So EastL gooooo :)

On 12 July 2015 at 14:14, BlueT - Matthew Lien - 練喆明 <
notifications@github.com> wrote:

> Hi @EastL <https://github.com/EastL> I think you can just send the pull
> request and let @agsh <https://github.com/agsh> decide to merge or not.
> :-)
> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agsh/onvif/issues/15#issuecomment-120702006>.
>



-- 
*Thomas PUJOLLE*
Developer & Electrical Science Student


<http://maps.google.com/maps?q=&hl=en>*Fr Mobile:* +336 49 88 03 44
*In Mobile:* +91 81977 67588
*Email:* thomas.pujolle@gmail.com
*http://fr.linkedin.com/in/thomaspujolle
<http://fr.linkedin.com/in/thomaspujolle>*

**Comment by agsh** [comment]
Hello guys! I'm on vacation right now. I'll come back to the computer in monday.
@Dermiste you can use @EastL's branch right now.

**Comment by agsh** [comment]
Done. Look `setSystemDateAndTime` method in [docs](http://agsh.github.io/onvif/Cam_.html)
