### ISSUE TITLE
I want to access public IP camera which is not in my local network

### ISSUE THREAD

**Issue by Yogita-Techspwan** [agsh/onvif#153]
Hi,

I have been able to discover and connect to the ONVIF cameras in my local network.
how can I access the camera which is placed in the remote location/another network/ global network/ public ONVIF camera

**Comment by chriswiggins** [comment]
Network discovery only works on the local layer 2 LAN. You'd just need to instantiate the camera using an IP address instead of via discovery.

**Comment by Asher978** [comment]
Quick question in the same scope as above.

what is the best way to provide the External IP for the site where the cam is located. I have set port forwarding on that site allowing a direct connection to the camera once i hit that port. 

`new CAM ({
      HOSTNAME: // i have tried the external ip but no luck
})`

Is there a diff method or way to instantiate this class with an external IP?
