### ISSUE TITLE
About setImagingSettings to set Iris and Focus

### ISSUE THREAD

**Issue by JqiangLiu** [agsh/onvif#164]
Hi, is it possible to set the iris and focus with this function?
I have read this code of this function,but i only see some params without iris and focus.

**Comment by agsh** [comment]
Hi! I think that answer is yes as iris and focus mentioned in the specs: https://www.onvif.org/ver20/imaging/wsdl/imaging.wsdl
Feel free to change the code and add lacking functionality! Don't forget to make PR after)

**Comment by JqiangLiu** [comment]
tx, i'll make PR in a few days

**Comment by chriswiggins** [comment]
Closing out old issue - if you'd like to send a PR @JqiangLiu that would be great!
