### ISSUE TITLE
Incomplete preset list

### ISSUE THREAD

**Issue by bartbutenaers** [agsh/onvif#175]
Dear,
I have an open-source Onvif integration for the Node-RED IOT framework, which is build on this `onvif` library.
I got yesterday a Github [issue](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes/issues/17) from somebody who has two problems with problems with his camera:
1. After some time `getPresets` suddenly starts return an empty array.
2. When a new preset has been added via the native app/webinterface of the ip camera, that new preset is not available in the output of `getPresets`.

So my first thought was that this library perhaps did some caching, which ran out of sync with the camera.  But when I debug it, then it seems to me that there is _**no caching**_.  Which means a request will be send every time to the camera.  Can you please confirm that this is correct?

If so, then I think there is an Onvif implementation bug in his Chinese camera...

Thanks!!!
Bart

**Comment by agsh** [comment]
Yes, caching is present, you need to call again getPresets. Calling this method can be falled by your cam, sorry(
