### ISSUE TITLE
how to get current PTZ values?

### ISSUE THREAD

**Issue by pppppppppppppppuuuuuurrrrrrreeeeeeee** [agsh/onvif#177]
i can't find a way for get the current ptz values.
is this possible in this package?

**Comment by chriswiggins** [comment]
Try to use the `getStatus` command and let us know how you go?

https://github.com/agsh/onvif/blob/master/lib/ptz.js#L167

**Comment by rodrigograca31** [comment]
```js
this.getStatus({}, (a, b) => {
			console.log(a);
			console.log(b);
		});
```
