### ISSUE TITLE
I can not add camera onvif Yoosee in MotioneyeOS

### ISSUE THREAD

**Issue by ivanjf1978** [agsh/onvif#182]
I have tried to are Cam era onvif Yoosee on motioneyeos in my raspberry pi 4B with 20200606 motioneyeos versión.

Camera Yoosee specifications

Specification:
Software： YOOSEE interesting
System structure： embedded Linux system, the structure of ARM chips
Chip：AK3918E (nk)
Pixel：200 w
The sensor resolution：2.0 M "GS2265 1920 x1080 by one-third
Lens：4 mm
Viewing Angle： 80 °
PTZ yuntai adjust Angle： horizontal, vertical direction of 355 ° ： 90 °
Can preset a： six
Video compression standard： h. 265/20 FPS
Video formats: PAL
Minimum illumination: 0.01 Lux @ (F2.0, VGC ON), O.L uxwith IR
Electronic shutter： automatically
Digital dynamic： wide support
Noise reduction：2 d and 3 d
Infrared lamp： four white six infrared lattice lamp Network connection：wi-fi wireless transmission (support IEEE802.11 b/g/n wireless protocol)
Night vision：Double filter automatic switching, 5-10 meters (owing to the different environment)
White light：APP end control：(1) open (2) shut down (3) automatically
(to be automatic mode, the IR - open automatically after the CUT CUT night vision infrared lamp, intelligent detection of the human body, intelligent opening/closing incandescent lamp)
Audio：Built-in microphone and speakers, omnidirectional noise reduction support two-way real-time audio transmission,
ADPCM audio compression standard, the adaptive streaming
Call the police: (1) motion detecting, push support images
(2), artificial intelligence researchers intrusion detection (optional)
ONVIF： Support ONVIF
Storage： TF card (maximum 128 g)： Cloud storage/cloud disk (optional)
The power supply. 12 v / 2 a
Working temperature：- 10 ℃ ~ + 50 ℃ work humidity: 95% RH or less)

I have tried all this URL with ispyconnect help but not working

Please. Help

Regards

Ivan

**Comment by RogerHardiman** [comment]
There is not enough information here to work out what is wrong.
What we need is for you to use the examples in this project to connect to the camera and share with us the XML replies and maybe log the XML sent out.
It also helps if you can put the camera online somewhere and we can do a quick test.

**Comment by RogerHardiman** [comment]
I'm going to clos this issue. The author was unable to give us any more information about the problem.
