### ISSUE TITLE
Return camera name, hardware, and urn during discovery 

### ISSUE THREAD

**Issue by aziztitu** [agsh/onvif#188]
Currently there doesn't seem to be any way to get the camera's device info during the discovery.

Is this planned to be supported in the future?

**Comment by RogerHardiman** [comment]
example4.js gives an example of receiving the discovery messages and the information you need is in the 'xml' parameter (the raw XML received).
So you probably want to parse the XML to extract more detail.
If you wanted to add this to the library so it returns the extra detail in the rinfo value, a PR would be great.


If you want more detail like serial numbers, you need to connect and authenticate with the camera and get the Device Information. Example2.js shows examples of connecting and getting DeviceInformation.

Finally, as an example of parsing the XML from Discovery, take a look at the onvif-audit project here on github.
I wrote it and it already has a parser that processes the Discovery XML in onvif-audit.js around line 110.

**Comment by RogerHardiman** [comment]
So, if you want to pull some bits from onvif-audit and put them into this onvif library, then a Pull Request would be welcome.

**Comment by RogerHardiman** [comment]
I've copied some sample code from onvif-audit over into example4 to show how to display the device make/model/hardware from the Discovery results.
