### ISSUE TITLE
Excuse me

### ISSUE THREAD

**Issue by yinwuyang** [agsh/onvif#192]
The methods in my imaging.js file are not available, and the URI module has no imaging module. I want to know if onvif has a video recording method. I hope someone can help me. Thank you

**Comment by RogerHardiman** [comment]
If the methods in imaging.js are not available it would indicate the camera does not return details about Imaging in the ONVIF GetCapabilities SOAP message.

ONVIF does have video recording methods, some of them are implemented in this library but help is needed to add more of the ONVIF API to this library.
