### ISSUE TITLE
Somebody help me! Error: read ECONNRESET

### ISSUE THREAD

**Issue by dragonview** [agsh/onvif#196]
**Somebody help me!**

**camera param:**
host:192.168.188.68
port:8000
**connect error:**
{ Error: read ECONNRESET
    at TCP.onread (net.js:660:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }

**the cam discovery info:**
Cam {
  _events: { newListener: [Function: bound ] },
  _eventsCount: 1,
  _maxListeners: undefined,
  hostname: '192.168.188.68',
  username: undefined,
  password: undefined,
  port: '8000',
  path: '/onvif/device_service',
  timeout: 120000,
  agent: false,
  preserveAddress: false,
  events: {},
  xaddrs:
   [ Url {
       protocol: 'http:',
       slashes: true,
       auth: null,
       host: '192.168.188.68:8000',
       port: '8000',
       hostname: '192.168.188.68',
       hash: null,
       search: null,
       query: null,
       pathname: '/onvif/device_service',
       path: '/onvif/device_service',
       href: 'http://192.168.188.68:8000/onvif/device_service' } ],
  timeShift: 1623376693788,
  services:
   [ { namespace: 'http://www.onvif.org/ver10/device/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/device_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/media/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/media_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/events/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/event_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver20/ptz/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/ptz_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver20/imaging/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/image_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver20/analytics/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/analytics_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/recording/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/recording_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/search/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/search_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/replay/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/replay_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/deviceIO/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/deviceIO_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/thermal/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/thermal_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/credential/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/credential_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/accessrules/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/accessrules_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/schedule/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/schedule_service',
       capabilities: [Object],
       version: [Object] },
     { namespace: 'http://www.onvif.org/ver10/receiver/wsdl',
       XAddr: 'http://192.168.188.68:8000/onvif/receiver_service',
       capabilities: [Object],
       version: [Object] } ],
  uri:
   { device:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/device_service',
        path: '/onvif/device_service',
        href: 'http://192.168.188.68:8000/onvif/device_service' },
     media:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/media_service',
        path: '/onvif/media_service',
        href: 'http://192.168.188.68:8000/onvif/media_service' },
     events:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/event_service',
        path: '/onvif/event_service',
        href: 'http://192.168.188.68:8000/onvif/event_service' },
     ptz:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/ptz_service',
        path: '/onvif/ptz_service',
        href: 'http://192.168.188.68:8000/onvif/ptz_service' },
     imaging:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/image_service',
        path: '/onvif/image_service',
        href: 'http://192.168.188.68:8000/onvif/image_service' },
     analytics:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/analytics_service',
        path: '/onvif/analytics_service',
        href: 'http://192.168.188.68:8000/onvif/analytics_service' },
     recording:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/recording_service',
        path: '/onvif/recording_service',
        href: 'http://192.168.188.68:8000/onvif/recording_service' },
     search:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/search_service',
        path: '/onvif/search_service',
        href: 'http://192.168.188.68:8000/onvif/search_service' },
     replay:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/replay_service',
        path: '/onvif/replay_service',
        href: 'http://192.168.188.68:8000/onvif/replay_service' },
     deviceIO:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/deviceIO_service',
        path: '/onvif/deviceIO_service',
        href: 'http://192.168.188.68:8000/onvif/deviceIO_service' },
     thermal:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/thermal_service',
        path: '/onvif/thermal_service',
        href: 'http://192.168.188.68:8000/onvif/thermal_service' },
     credential:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/credential_service',
        path: '/onvif/credential_service',
        href: 'http://192.168.188.68:8000/onvif/credential_service' },
     accessrules:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/accessrules_service',
        path: '/onvif/accessrules_service',
        href: 'http://192.168.188.68:8000/onvif/accessrules_service' },
     schedule:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/schedule_service',
        path: '/onvif/schedule_service',
        href: 'http://192.168.188.68:8000/onvif/schedule_service' },
     receiver:
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.188.68:8000',
        port: '8000',
        hostname: '192.168.188.68',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/receiver_service',
        path: '/onvif/receiver_service',
        href: 'http://192.168.188.68:8000/onvif/receiver_service' } },
  media2Support: false }

**Comment by RogerHardiman** [comment]
Q1 - what camera are you connecting to
Q2 - what version of the ONVIF Library - ie when did you clone it from github and which branch (eg master or roger-branch)

**Comment by dragonview** [comment]
> Q1 - what camera are you connecting to
A small brand of ip camera， lan ip：192.168.188.68

> Q2 - what version of the ONVIF Library - ie when did you  clone it from github and which branch (eg master or roger-branch)
ONVIF version：2.4
GitHub： master，2021/6/1

**Comment by RogerHardiman** [comment]
In the Cam object you put in the first post, I can see the username is null and the password is null.

ONVIF allows some commands to be used without a username and password.
One of them is GetCapabilities, which returns all the XAddr information you can see on the Cam Object.
But after calling GetCapabilities, the rest of the ONVIF commands need a username and password, unless you have a very cheap ONVIF camera that does not implement security.

We normally get a SOAP error back when the username is invalid (or missing).
Maybe your camera just closes the network socket giving the ECONNRESET

I'd need to have remove access to the camera to verify this.

What happens when you do have a username and password?

**Comment by NdiayeeCheikh** [comment]
I HAVE THE SAME PROBLEM, BUT I'VE PUT USERNAME AND PWD:

const server = require('http').createServer((req, res) =>
  res.end(`
<!DOCTYPE html><body>
<canvas width='640' height='480' />
<script src="/socket.io/socket.io.js"></script><script>
const socket = io(), ctx = document.getElementsByTagName('canvas')[0].getContext('2d');
socket.on('data', (data) => {
const img = new Image;    
const url = URL.createObjectURL(new Blob([new Uint8Array(data)], {type: 'application/octet-binary'}));
img.onload = () => {
URL.revokeObjectURL(url, {type: 'application/octet-binary'});
ctx.drawImage(img, 100, 100);
};
img.src = url;
});
</script></body></html>`));
const { Cam } = require('onvif/promises'), io = require('socket.io')(server), rtsp = require('rtsp-ffmpeg');

server.listen(6147);

const cam = new Cam({username: 'user1', password: 'user.111', hostname: '192.168.1.65', port: 554, timeout: 60000 });
(async() => {
await cam.connect();
const input = (await cam.getStreamUri({protocol:'RTSP'})).uri.replace('://', `://${cam.username}:${cam.password}@`);
const input2="rtsp://user1:user.111@192.168.1.65:554/live";
const stream = new rtsp.FFMpeg({input, resolution: '320x240', quality: 3});
io.on('connection', (socket) => {
const pipeStream = socket.emit.bind(socket, 'data');
stream.on('disconnect', () => stream.removeListener('data', pipeStream)).on('data', pipeStream);
});
setInterval(() => cam.absoluteMove({
x: Math.random() * 2 - 1,
y: Math.random() * 2 - 1,
zoom: Math.random()
}), 3000);
})().catch(console.error);

HERE IS THE ERROR:
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:216:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
