### ISSUE TITLE
what get metadata onvif

### ISSUE THREAD

**Issue by Hareis** [agsh/onvif#201]
what get metadata onvif?

**Comment by RogerHardiman** [comment]
ONVIF metadata can come from several difference places.
1) it can be included in the RTSP as an additional stream along side the Video and Audio. I know the NodeJS RTSP client called Yellowstone has some code to receive the metadata over RTSP as I wrote it a year or two ago. Yellowstone will deliver the raw metadata from the RTP packets.

2) some metadata can be included as data values in ONVIF Events.
This library (agsh/onvif) can subscribe to ONVIF Events and receive the ONVIF Event XML messages.
On my Axis cameras's I've seen ONVIF Events with co-ordinates for the bounding boxes of objects.
There is an example program (example6.js) that will list ONVIF events and then receive the events. You may need to add additional support for events with the metadata.

Let us know how you get on.

**Comment by Hareis** [comment]
@RogerHardiman 

![企业微信截图_16303773136802](https://user-images.githubusercontent.com/11290701/131432660-f9597ac8-1ac9-40a8-a357-f0d13384b1ea.png)

I was thinking that this might not be an event. Sorry, I didn’t see the custom event monitoring in example6
