### ISSUE TITLE
dev branch and backward API compatibility

### ISSUE THREAD

**Issue by BlueT** [agsh/onvif#21]
Due to 'API changes crash things',
I would like to suggest to have a 'dev' branch for new feature and API changes or experiments.
And before release, there might be better to have some 'backward API compatibility' for users to prepare the transation process. :-)

I was trying to clarify and debug a crash when IPcam only has H264 encoding (no MPEG4), but suddently the world changed. lol

**Comment by agsh** [comment]
I agree with you, but now I'm trying to release 0.4 version instead of 0.3 from npm. So master branch in git which presents 0.4 version consists many changes and improves. Please wait until 0.4 release.
After all every 'dev' branch wil be merged into 'master'.

**Comment by agsh** [comment]
Also that changes made for compatibility with current responses from `getVideoEncodeConfigurations` and `getVideoEncodeConfiguration` methods. Just look at the tests: https://github.com/agsh/onvif/blob/master/test/media.coffee

**Comment by BlueT** [comment]
OK cool :+1

**Comment by BlueT** [comment]
@agsh as 0.4 has been released last year, I guess it's time for a dev branch? :-)

**Comment by agsh** [comment]
Sure, it's done!
