### ISSUE TITLE
Get some info of the device without username/password

### ISSUE THREAD

**Issue by namnm** [agsh/onvif#210]
Hi

Do we have someway to get some information of the device without username/password?
Like camera model name and some basic info to display on the UI so user can input username/password for that camera afterward? Right now on probe I can only have the local ip address which is difficult for the user to distinguish between multiple cameras.

**Comment by RogerHardiman** [comment]
There are two places to get information without username/password
1) The reply to the Discovery Message includes XML which has lots of details about the device and often includes a Make/Model and a UUID.

2) The ONVIF Specification   http://www.onvif.org/specs/core/ONVIF-Core-Specification.pdf   lists all the ONVIF Methods.
Search this document for "PRE_AUTH" . It will show you the ONVIF Functions you can call without authentication.
They include GetCapabilities and GetSystemDateAndTime, but it does not include GetDeviceInformation.


Normally you rely on the XML reply from the Discovery Message.

There is sample code in the github project called "onvif-audit" which parses the XML
https://github.com/RogerHardiman/onvif-audit/blob/master/onvif-audit.js
Line 97 onwards
