### ISSUE TITLE
How do I display an RTSP URI on Reactjs

### ISSUE THREAD

**Issue by Luisquii** [agsh/onvif#237]
Hi

I'm new with onvif protocol and also rtsp protocol.

My goal is to stream my IP camera to Reactjs

After following the example.js when I get the stream URI, I'm receiving an rtsp uri:

[example here](https://github.com/agsh/onvif/blob/master/examples/example.js)

`{
  uri: 'rtsp://192.168.0.109/Streaming/Channels/101?transportmode=unicast&profile=Profile_1' 
}`

As long as I understand is not possible to reproduce an rtsp stream on browser, at least not straight forward.

Am I supposed to get an URI different than rtsp?

What are my possibilities?

I'm using a hikvision camera.

**Comment by agsh** [comment]
Hi! The simplest way, if you are common with javascript, is to use this: https://github.com/agsh/rtsp-ffmpeg or some similar library based on https://ffmpeg.org/
For the highload projects I can suggest https://www.kurento.org/ for example
