### ISSUE TITLE
absoluteMove() question

### ISSUE THREAD

**Issue by Irrelon** [agsh/onvif#26]
Hi there, first let me say thank you for an excellent library!

I have a PTZ cam and have been playing with getting PTZ functionality working with this library. I tested the absoluteMove() method and the camera does indeed move but I am a bit confused about the maximum value of -1 to 1. I would have thought that an absolute movement would have given actual PTZ values rather than in a normalised range of -1 to 1.

When I tell the camera to move {x: 1, y: 0, zoom: 0} it will tilt down by 1 unit... this seems a bit weird to me since it will not accept any value above 1. How do you achieve setting exact values when you only have a range from -1 to 1?

Many thanks!

**Comment by agsh** [comment]
Hello!
I found this values from the specification: http://www.onvif.org/specs/srv/ptz/ONVIF-PTZ-Service-Spec-v210.pdf in `5.7.1.1 Generic Pan/Tilt Position Space `

**Comment by Irrelon** [comment]
Many thanks, I'll check out the doc and see what it relates to :+1:
