### ISSUE TITLE
Allow a timeout to be specified when creating a Cam instance

### ISSUE THREAD

**Issue by scriby** [agsh/onvif#27]
If the camera changes IP addresses, it can take a couple minutes to for the request to timeout when trying to connect to it. That's quite a while to wait to receive an error, so it would be nice to be able to configure a timeout for the http request.

**Comment by chriswiggins** [comment]
This should be fairly straightforward. I'll submit a PR for it shortly

**Comment by scriby** [comment]
Thanks! Verified this is working today.
