### ISSUE TITLE
@yuxiaolejs Fix lint errors

### ISSUE THREAD

**Issue by agsh** [agsh/onvif#273]
@yuxiaolejs Oh, and also fix lint errors, please: https://github.com/agsh/onvif/actions/runs/3729451314

_Originally posted by @agsh in https://github.com/agsh/onvif/issues/270#issuecomment-1357306792_

**Comment by yuxiaolejs** [comment]
@agsh Sorry! I used default formmater in VS code! I have reformatted the document with eslint, and it should be fine now!
