### ISSUE TITLE
Compatibility of Axis M5000-G PTZ Camera.

### ISSUE THREAD

**Issue by sirish-gambhira** [agsh/onvif#293]
Hello all.

I am planning to buy Axis Communications M5000-G 15MP PTZ Network Dome Camera. I want to programmatically control the pan, tilt, zoom movements of the camera using languages like java-script or python. That is, I want to send commands to the camera to pan to a certain location, tilt to a certain angle or zoom to a certain extent without any hardware dependency. The [datasheet](https://www.axis.com/dam/public/15/ec/c1/datasheet-axis-m5000-g-ptz-camera-en-US-397901.pdf) for the camera states that it is compliant with ONVIF profiles G, M, S, T.
I want to make sure that this repository supports the camera movement before I purchase it. 

Thanks in advance. 

Tagging @agsh and @RogerHardiman for better reach.

**Comment by RogerHardiman** [comment]
Hi
I use the library with several Axis PTZ cameras.
I also know several of the staff at the UK office of Axis and am visiting their offices in the UK next month for a meeting.

The library will work with Axis with the type of PTZ where you say "start moving at speed X" and then a bit later say "stop moving"
The library also supports moving to an absolute position. eg goto position 180 degrees, Pan, 33 degrees tilt and the Zoom at at 55%

I use the library from my own NodeJS application (written in Javascript) with Axis cameras.

The only thing I don't know how well the library will work is that the M5000 has 4 images (3 sensors for the panoramic image and 1 sensor on the PTZ).
But if there are problems, I'm am interested in debugging the library to make sure it works. I would need remote access to the camera.

Roger

**Comment by Sirish07** [comment]
Hi @RogerHardiman.

Thank you for your reply. 

I am happy to hear that the Axis PTZ cameras are compatible with the library. The following is my use-case scenario, and I would like to know if you have any cheaper/better recommendations suitable for my setting.

Scenario: I would like the PTZ camera to cover an indoor office space of 3000 sq ft (approximately). I would like to build custom events to detect the people in the scene and zoom onto their faces (if required). The camera movement speed and optical zoom are a priority. 

I have the following cameras already available and would like to know their compatibility with the library as well:
1. [Panasonic AW-HE40HWE camera](https://pro-av.panasonic.net/en/sales_o/camera/aw-he40/)
2. [Sony BRC-H700 camera](https://pro.sony/en_GB/products/ptz-network-cameras/brc-h700)

**Comment by RogerHardiman** [comment]
Your project sounds interesting. I assume you'll have an overview camera, then run some software to detect people and then drive the Pan, Tilt and Zoom to an "absolute position".

Unfortunately I have never used the Panasonic or Sony cameras you mentioned to so do not know if they will be suitable.
You would have to try them.

The library has been used with two other Panasonic PTZ cameras and with a Sony camera with E-PTZ
