### ISSUE TITLE
PTZ Presets Bug with presets that have the same name

### ISSUE THREAD

**Issue by Craytor** [agsh/onvif#340]
If you have multiple presets that have the same "name" but different id's, the current solution is using an index within the array for the preset name. This is not a viable solution as some cameras may have a default name of "managed" (i.e. reolink), where the actual id of the ptz preset will have to be a different number.

The problem lies here: https://github.com/agsh/onvif/blob/master/lib/ptz.js#L36.

The proposed solution is to swap the key with the value and vice versa.

**Comment by Craytor** [comment]
This has been addressed in PR #341.

**Comment by agsh** [comment]
@Craytor Hello! Thanks for the notice and PR! I've looked through the code, this change doesn't affect anything, so it's ok.
I have only one question in the review. https://github.com/agsh/onvif/pull/341/files/54f08ae0e6279de54a1e506dd469694087786f61 And then I'll merge it.

**Comment by Craytor** [comment]
Fixed per PR #341.

Closing.
