### ISSUE TITLE
GetScopes failed.

### ISSUE THREAD

**Issue by BlueT** [agsh/onvif#39]
I'm working on testing node-onvif with rpos https://github.com/BreeeZe/rpos
I found that GetScopes failed. https://github.com/BreeeZe/rpos/issues/16

@RogerHardiman opened a PR fixing the problem https://github.com/agsh/onvif/pull/38

**Comment by BlueT** [comment]
I've tested #38 and it works.
Hope @agsh can merge it soon. :-)

**Comment by RogerHardiman** [comment]
Thanks for testing.I also found GetHostname had the same bug so fixed that too. All the other xml code looked fine.

In my office had one IP camera that accepted the bad xml (IPS Eye01) and two cameras that rejected the bad xml (axis m7001 and RPOS)

-------- Original message --------

**Comment by RogerHardiman** [comment]
Merge of #38 is now complete
