### ISSUE TITLE
Improvement: RTSP address re-write for NAT devices

### ISSUE THREAD

**Issue by RogerHardiman** [agsh/onvif#41]
I am connecting to an NVT via a public IP address over the internet eg  8.8.8.8
The NVT is accessed via a NAT broadband router and has a 192.168.0.10 local address.

The NVT returns XAddrs with 192.168.0.10 but I notice this ONVIF libary ignores the IP address in the XAddrs and uses the original IP address used to connect to (eg the 8.8.8.8 address)

When asking for a RTSP stream (GetStreamUri) it returns a RTSP string with 192.168.0.10

As an Improvement it would be good to have a function to re-write the RTSP string, replacing the 192.168.0.10 with the public IP address (eg 8.8.8.8).
ONVIF Device Manager works like this

**Comment by BlueT** [comment]
IMO it's better to keep the original returned IP somewhere at least, instead of just overwriting it.
Or, let users choose / replace it by their own.

**Comment by RogerHardiman** [comment]
I was thinking of a function to re-write the address that the higher 
level function can call or can be enabled with an option.
If the returned address is 192.x, 10.x or 172.x (the specific ranges) 
and if the ONVIF address is a public address (ie not 192.x, 10.x or 
172.x) and if the option is enabled it would replace with the public 
address.





On 18/06/2016 21:36, BlueT - Matthew Lien - 練喆明 wrote:
>
> IMO it's better to keep the original returned IP somewhere at least, 
> instead of just overwriting it.
> Or, let users choose / replace it by their own.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/agsh/onvif/issues/41#issuecomment-226963579>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/AJszIejgnmYC31NtY2HB7k5VLBwr54FBks5qNFbcgaJpZM4IgRsR>.
>

-- 
Roger Hardiman
RJH Technical Consultancy Ltd
07968 245759
www.rjh.org.uk
roger@rjh.org.uk

**Comment by agsh** [comment]
I've added `preserveAddress` property for the constructor. I hope it helps.
