### ISSUE TITLE
Onvif browser support

### ISSUE THREAD

**Issue by brunogoossens** [agsh/onvif#45]
I want to use this module in my frontend application written in Aurelia.
I use ES6 to load the module
```
import {Onvif} from 'onvif';
```

I get this error in de console:
Error: Node dgram module not supported in browsers.

Is there a way to avoid this module?

**Comment by chriswiggins** [comment]
Hi @brunogoossens - There is a potential to add a special use case for browsers where dgram isn't available. This module is used for WS-Discovery (UDP) so this wouldn't work in a browser.

Why don't you have a play to see if you can exclude it and then let us know how you get on? I think you're the first person that wants to run it in a browser

**Comment by agsh** [comment]
@brunogoossens, you can't run this lib in the browser because it works with UDP and TCP/IP protocols. But you can use something like http://nwjs.io/ with node.js under the hood
