### ISSUE TITLE
Set camera resolution?

### ISSUE THREAD

**Issue by larsenglund** [agsh/onvif#46]
Hi, is it possible to set the camera resolution with this library?
I have a onvif ip camera ([Sricam](http://goo.gl/44aChK)) that comes with a horrible android app. If I capture it's rtsp h264 stream with avconv or ffmpeg I get the resolution that I last selected in the android app. I have sniffed the packets the app sends and it does indeed send a start/setup packet with the desired resolution. Can I do the same with this library?

**Comment by RogerHardiman** [comment]
Could you paste here the packet you sniffed with the desired resolution in please?
I can then check it is an ONVIF message, or check if it an RTPS setup message.

Thanks

**Comment by agsh** [comment]
Lars, hi! You can set camera resolution via setVideoEncoderConfiguration method. Please see onvif specs for details.

**Comment by BlueT** [comment]
Video resolution can be set, we do it every day.
@larsenglund if you got any errors, could you describe more and paste error message?

**Comment by larsenglund** [comment]
@BlueT That's excellent, how do you do it, I can only find get-methods in the API docs at http://agsh.github.io/onvif/

**Comment by larsenglund** [comment]
Sifted through the source now and found the method @agsh mentioned, silly assumption of me that the API docs would be up to date..

**Comment by chriswiggins** [comment]
@larsenglund you're more than welcome to submit a PR to update the docs :-)

**Comment by larsenglund** [comment]
@chriswiggins I might do that :) (I wasn't being ironic if it sounded like I was, it is silly to expect that from a free open source project, I'm just thankfull it exists at all)

**Comment by agsh** [comment]
Sorry guys for outdated documentation, but `setVideoEncoderConfiguration` method presents there http://agsh.github.io/onvif/Cam_.html. Without several option mentioned in jsdoc comments. I'll generate fresh docs in this monday.

**Comment by mjn9** [comment]
How to change resolution of a camera using libonvif library
