### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by sousandrei** [agsh/onvif#48]
For some reason the script gets stuck in this ocasion. Cam.js - line 186
It sould land in the callback on line 178 and timeout after the set time but it doesnt :/

**Comment by kruschid** [comment]
Same problem here. Instead of printing the error to console in some cases, the script should call the callback function for every case, right? Might be useful for debugging but it isn't in production mode. :-(

Cam.js: lines 185 - 193
		/* address, port number or IPCam error */
		if (err.code === 'ECONNREFUSED' && err.errno === 'ECONNREFUSED'  && err.syscall === 'connect') {
			console.error(err);  
		/* network error */
		} else if (err.code === 'ECONNRESET' && err.errno === 'ECONNRESET'  && err.syscall === 'read') {
			console.error(err);
		} else {
			callback(err);
		}

**Comment by agsh** [comment]
I strongly agree with you, this wasn't my patch, missed this out. Replaced `console.error` with callbacks but saved `if` cases for debugging purposes https://github.com/agsh/onvif/commit/ce1e4eb076a98fed28258f4c3a4444a86a057735

**Comment by BlueT** [comment]
ah, sorry for that.
I asked @sunnyworm to send PR if he fixed the connection refuse bug with a broken firmware on one of our IPcam, but I forgot to do code review...

Will mention this to him and prevent any further bug like this.
Thanks @agsh for fixing!

**Comment by scriby** [comment]
Ran into this today as well, thanks for fixing

**Comment by agsh** [comment]
Done! 0.4.3
