### ISSUE TITLE
Authentication error in ONVIF enabled Dahua Camera

### ISSUE THREAD

**Issue by stanzheng** [agsh/onvif#62]
Make: Dahua
Camera Model: [SD6A8240-HNI](http://www.cctv-mall.com/sd6a220-hni-dahua-sd6a220-hni-2mp-full-hd-20x-30x-network-ir-auto-track-ptz-ip-camera-dh-sd6a220-hni)
ONVIF 2.4.1 supported camera 

Running the example code changing the `hostname`, `user`, `pass`, with my login credentials, I hit an error in the `function(err)` callback. 

> Error: ONVIF SOAP Fault: Sender not Authorized

I checked ONVIF the camera settings and ONVIF support is enabled. Is there some settings regarding how the credentials are hashed that could be different between cameras? I'm not too familiar with IP cameras and but I would like to contribute a fix so it'd work with this camera model line.

Thank you 

full stack trace below 

```

Error: ONVIF SOAP Fault: Sender not Authorized
    at /Users/stanleyzheng/Code/Code/cam/node_modules/onvif/lib/utils.js:83:12
    at Parser.<anonymous> (/Users/stanleyzheng/Code/cam/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/Users/stanleyzheng/Code/cam/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/Users/stanleyzheng/Code/cam/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/Users/stanleyzheng/Code/cam/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/Users/stanleyzheng/Code/cam/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/Users/stanleyzheng/Code/cam/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/Users/stanleyzheng/Code/cam/node_modules/xml2js/lib/xml2js.js:508:31)

```

**Comment by chriswiggins** [comment]
Would it be possible for you to capture the traffic between your machine and the camera with Wireshark so we can see the exact request/response?

If you can capture that, could you also try connecting to the camera with Onvif Device Manager (Windows Application) and capture that traffic too so we can compare how the authentication is happening?

Chris


On 9/10/2016, at 2:25 AM, Stanley Zheng <notifications@github.com<mailto:notifications@github.com>> wrote:


Make: Dahua
Camera Model: SD6A8240-HNI<http://www.cctv-mall.com/sd6a220-hni-dahua-sd6a220-hni-2mp-full-hd-20x-30x-network-ir-auto-track-ptz-ip-camera-dh-sd6a220-hni>
ONVIF 2.4.1 supported camera

Running the example code changing the hostname, user, pass, with my login credentials, I hit an error in the function(err) callback.

Error: ONVIF SOAP Fault: Sender not Authorized

I checked ONVIF the camera settings and ONVIF support is enabled. Is there some settings regarding how the credentials are hashed that could be different between cameras? I'm not too familiar with IP cameras and but I would like to contribute a fix so it'd work with this camera model line.

Thank you

full stack trace below


>
> Error: ONVIF SOAP Fault: Sender not Authorized
>     at /Users/stanleyzheng/Code/freelance/scratch/node_modules/onvif/lib/utils.js:83:12
>     at Parser.<anonymous> (/Users/stanleyzheng/Code/freelance/scratch/node_modules/xml2js/lib/xml2js.js:489:18)
>     at emitOne (events.js:96:13)
>     at Parser.emit (events.js:188:7)
>     at Object.onclosetag (/Users/stanleyzheng/Code/freelance/scratch/node_modules/xml2js/lib/xml2js.js:447:26)
>     at emit (/Users/stanleyzheng/Code/freelance/scratch/node_modules/sax/lib/sax.js:640:35)
>     at emitNode (/Users/stanleyzheng/Code/freelance/scratch/node_modules/sax/lib/sax.js:645:5)
>     at closeTag (/Users/stanleyzheng/Code/freelance/scratch/node_modules/sax/lib/sax.js:905:7)
>     at Object.write (/Users/stanleyzheng/Code/freelance/scratch/node_modules/sax/lib/sax.js:1449:13)
>     at Parser.exports.Parser.Parser.parseString (/Users/stanleyzheng/Code/freelance/scratch/node_modules/xml2js/lib/xml2js.js:508:31)



-

**Comment by agsh** [comment]
@stanzheng did you resolve your issue?

**Comment by stanzheng** [comment]
Ah i haven't had the time to try @chriswiggens suggestion but I hope to get some time in this week to take a look. 

thanks for following up!

**Comment by xanview** [comment]
Any luck? :)

**Comment by tolland** [comment]
I found that Dahua onvif was using a different set of credentials for web access, and the onvif access. The default user/pass for onvif was admin/admin regardless of what it was changed to in the web gui.
See here for other users reporting the same;
https://sourceforge.net/p/onvifdm/discussion/1246119/thread/9a2a918a/

**Comment by hawkeye64** [comment]
The Axis cameras are the same. You can't use any of the normally created users, you have to go to the admin section and under Onvif/Users and then add one (there isn't one by default). That's the user you then use for onvif authentication.

Someone should close this issue. @chriswiggins ?

**Comment by chriswiggins** [comment]
Yep this is a common theme emerging across lots of camera firmware. 

If anyone else hits this error, check your camera / ONVIF device doesn’t need separately-created ONVIF users.
