### ISSUE TITLE
Bug in parsing XAddrs in Discovery

### ISSUE THREAD

**Issue by RogerHardiman** [agsh/onvif#63]
I have some ONVIF devices which respond to a WS-Discovery but in the discovery XML reply there are TWO different XAddrs with a space between them.
The parsing code in discovery.js cannot handle this

Axis Encoder return this...
`<d:XAddrs>http://169.254.119.177/onvif/services http://192.168.1.125/onvif/services</d:XAddrs>
`
Axis Q1615 returns this...
`<d:XAddrs>http://192.168.1.102/onvif/device_service http://169.254.125.197/onvif/device_service</d:XAddrs>`

Bosch Encoder returns this...
`<d:XAddrs>http://192.168.1.124:80/onvif/device_service https://192.168.1.124:443/onvif/device_service</d:XAddrs>`

One device (360 Vision Pred) only has one entry in the XAddr and so parses fine

The problem looks like this line in discovery.js

```
                                                var camUri = url.parse(data.probeMatches.probeMatch.XAddrs);
                                                cam = new Cam({
                                                        hostname: camUri.hostname
                                                        , port: camUri.port
                                                        , path: camUri.path
                                                });

```

followed by
`Discovery.emit('device', cam, rinfo, xml);
`

It needs to detect if there are multiple XAddrs (some form of Split on Whitespace) and either loop through them, with multiple Emits() or turn the cam parameter into an array.

**Comment by Climax777** [comment]
I don't think it really is a bug. But I've seen that some devices respond with an IPv4 and IPv6 address in the same XAddrs tag. I simply split the string myself and use the IPv4 one.

**Comment by Climax777** [comment]
@RogerHardiman I think the best could be to select the first one after the split and then bundle all of them in a new field, for example: `additionalXAddrs`

**Comment by RogerHardiman** [comment]
Sorry, I should have explained the bug.
the parser breaks the XAddr down into Hostname, Port and Path.
On devices with multiple XAddrs I get this

hostname = 192.168.1.102
port = 80
path = /onvif/device_service%20http://169.254.125.197/onvif/device_service

So the second XAddr finds its way into the 'path'


I noticed on the Axis M7001 the first XAddr was the 169.x.x.x link-local address and the XAddr was the one I wanted. On the Q1615 the first XAddr was the one I wanted and the 2nd XAddr was the 169.x.x.x link-local address
Bosch return two XAddrs where the second one is for HTTPS (port 443)

So if we just return one address, I'd prefer to push the link local into the additionalfaddrs field

**Comment by agsh** [comment]
What about splitting XAddr by space and emitting `device` event several times for each address?

**Comment by Climax777** [comment]
I don't think that is accurate as all of them refer to the same device.
Naively using the results will cause headaches and lots of streams probably

**Comment by RogerHardiman** [comment]
I thought about splitting the XAddr and having an 'emit' for each too but thought it better to keep them together as Climax777 suggested.

**Comment by agsh** [comment]
My suggestion is here in `dev` branch: 9f1ea94. What do you think?

**Comment by Climax777** [comment]
Looks good to me! Does it solve the issue?
