### ISSUE TITLE
How to run the test

### ISSUE THREAD

**Issue by 496126321** [agsh/onvif#68]
I download the latest ONVIF package and follow the step to install but failed to run the test.  please help how to solve this.
1. go to the unzip directory and run "npm install" to download all dependent library for this project. 
By checking folder node_modules, all modules download successfully.
2. As the document said  I run "npm test" to test it , it failed with attached snapsh
![1](https://cloud.githubusercontent.com/assets/9329724/20738913/9ca22f92-b6f1-11e6-9e92-5ae45df45000.png)

Any one help how to runt the test?

**Comment by agsh** [comment]
Hi! I think that this is issue with windows paths. But windows shell can convert slash symbols into backslashes... So first step is to replace '/' symbols to '\' in 'script' section of package.json. Sorry I haven't got windows to test it.
Also please check the run directory because the paths is relative.

**Comment by nbxtruong** [comment]
> Hi! I think that this is issue with windows paths. But windows shell can convert slash symbols into backslashes... So first step is to replace '/' symbols to '' in 'script' section of package.json. Sorry I haven't got windows to test it.
Also please check the run directory because the paths is relative.

I have error Can't open lib/*.js. I run on windows 10. So, How can  I fix it.

**Comment by RogerHardiman** [comment]
The tests have been fixed and work on windows 10. I was making extensive use of the tests on windows 10 when updating the Events code recently.

So closing this down but if you still have problems with the latest version then please openter a new issue report.
