### ISSUE TITLE
try to use getSnapshotUri

### ISSUE THREAD

**Issue by serafimdasaudade** [agsh/onvif#69]
Hi, 
I'm new in nodejs.
I have no problem running the examples with my avigilon 2.0w-h3ptz-dp20. Now I'm trying to use the method getSnapshotUri, with no success. 
Can you guys show some examples.

tks,

**Comment by serafimdasaudade** [comment]
Well, I try the getSanphotUri on a Sony and it work. Maybe the avigilon Cam got some problem on this method.

tks.

**Comment by agsh** [comment]
You can find possible errors in the first callback argument
```js
cam.getSnapshotUri((err, data) => {
  if (err) {
    console.error(err);
  }
});
```
