### ISSUE TITLE
How can I save a jpg image from the camera?

### ISSUE THREAD

**Issue by cristhiangr** [agsh/onvif#75]
Hi, Thanks for sharing your project, I have the following situation: I can see the image in the browser, but I can not save the jpg on my disk, it gives me authorization error (401).

new Cam({
		hostname: getIP(),
		username: getUser(),
		password: getPassword(),
		port: getPort()
		}, function(err) {
			if (err) {
				console.log('Connection Failed for ' + obtenerIP() + ' Port: ' + obtenerPuerto() + ' Username: ' + obtenerUsuario() + ' Password: ' + obtenerPassword());
				return;
			}
			console.log('CONNECTED');
			this.absoluteMove({
				x: 1
				, y: 1
				, zoom: 1
			});
				
			this.getSnapshotUri({protocol:'RTSP'}, function(err, stream) {
					
				saveImage(stream.uri);

			});
		});

function saveImage(rutaOnvifImagen){

	var file = fs.createWriteStream("miImagen.jpg");

	request(rutaOnvifImagen).pipe(file);

}

This code generates a jpg file but it is not an image,   When I open it with a notepad it contains the following message:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>

Thanks for your help

**Comment by chriswiggins** [comment]
Hi @cristhiangr - likely because you're using request without any authentication set. Try setting the username and password in the request library as well:

```
request.get(rutaOnvifImagen, {
  'auth': {
    'user': getUser(),
    'pass': 'getPassword()
  }
});

```

Let me know how you get on

**Comment by cristhiangr** [comment]
Hi @chriswiggins Thanks for answering.  I implemented what you indicate, but the result is the same.  
I'm new to Node js,  Until 2 days ago I didn't know what it was, but I'm looking for a solution to take images from Onvif and this looks good.

This is my code:

var http = require('http'),
	Cam = require('onvif').Cam,
	fs = require("fs"),
	request = require('request');

init();

function init(){
       if(checkIP() && checkUser() && checkPassword() && checkPort()){
		new Cam({
					hostname: getIP(),
					username: getUser(),
					password: getPassword(),
					port: getPort()
				}, function(err) {
					if (err) {
						console.log('Connection Failed for ' + getIP() + ' Port: ' + getPort() + ' Username: ' + getUser() + ' Password: ' + getPassword());
						return;
					}
					console.log('CONNECTED');
					this.absoluteMove({
						x: 1
						, y: 1
						, zoom: 1
					});
				
					this.getSnapshotUri({protocol:'RTSP'}, function(err, stream) {
					
						saveImage(stream.uri);

					});
				});
	}
	else
	{
		console.log("datos de inicio incompletos o no validos");
	}
}

function saveImage(pathOnvifImage){

	request.get(rutaOnvifImagen, {
	  'auth': {
		'user': getUser(),
		'pass': getPassword()
	  }
	});

	var file = fs.createWriteStream("miImagen.jpg");

	request(pathOnvifImage).pipe(file);
	
}

Thanks,

**Comment by agsh** [comment]
Thanks, Chris, that you still reply for every message, I really appreciate you for that. @chriswiggins

**Comment by agsh** [comment]
@cristhiangr, JavaScript is an asynchronous language, so you should put your getSnapshotUrl under the callback, cause communication with camera is async.
You can try to cover it to promise with bluebird library and use async-await with the es7 features
I'll try to add this ASAP
This is all that I can see in your code, that you send

**Comment by chriswiggins** [comment]
Yeah put your whole script in a Gist and we can comment and try and help you with your issues

Sent from my iPhone

On 2/06/2017, at 6:50 AM, Andrew Laptev <notifications@github.com<mailto:notifications@github.com>> wrote:


@cristhiangr<https://github.com/cristhiangr>, JavaScript is an asynchronous language, so you should put your getSnapshotUrl under the callback, cause communication with camera is async.
You can try to cover it to promise with bluebird library and use async-await with the es7 features
I'll try to add this ASAP
This is all that I can see in your code, that you send

**Comment by cristhiangr** [comment]
Thanks, I created a gist and put what the code there.  This is the link [https://gist.github.com/cristhiangr/69dd61ab9b94ed23675abfcf0003175c](url)  Thank you very much @agsh  and @chriswiggins .  I'm reading about bluebird, but I still don't know what I should do.

**Comment by chriswiggins** [comment]
Hi @cristhiangr,

I think I've found the problem. Try this in your save image function:

```javascript
function saveImage(pathOnvifImage){
	var file = fs.createWriteStream("miImagen.jpg");

	request.get(pathOnvifImage, {
	  'auth': {
		'user': getUser(),
		'pass': getPassword()
	  }
	}).pipe(file);
	
}
```

What you were doing was making two requests to the same place, one with authentication and one without, and saving the one without authentication. Let me know if this works

**Comment by cristhiangr** [comment]
@chriswiggins thank you very much for continuing to respond, I implemented the changes you suggest but I still have the same result

**Comment by agsh** [comment]
@cristhiangr, can you post here your `pathOnvifImage` string?
Also please check the authorization headers of GET response.

**Comment by cristhiangr** [comment]
hi @agsh ofcourse, this is the path onvif (stream.uri), http://192.168.1.251/onvif-cgi/jpg/image.cgi?resolution=1280x1024&compression=30  that I get with the getSnapshotUri method.   If I public this code like a webserver effectively I see the image in that web path.

**Comment by agsh** [comment]
So you can open an image via this url in the browser?
Try this code
```js
request('http://192.168.1.251/onvif-cgi/jpg/image.cgi?resolution=1280x1024&compression=30')
.pipe(fs.createWriteStream('miImagen.jpg'));
```

**Comment by cristhiangr** [comment]
Hello @agsh , excuse the delay in replying,  I implemented that, but I still have the same result.  Yes I can open an image via this url in the browser.  I'll record a video and upload it so you can see in detail what happens.

Thanks

**Comment by cristhiangr** [comment]
@agsh, @chriswiggins , today I tested with a vivotek camera and a hikvision camera, and I was able to save the image without any problem.  However, with the camera axis, which I have had all this time, I still have the problem of authorization to save the image.

**Comment by hawkeye64** [comment]
In case anyone finds this based on an issue they are having I have written a gist. The issues you might encounter are:
  1. Connecting to a camera (how to use authorization)
  2. Getting the snapshotUri
  3. Getting a snapshot
    a. How to get the raw data back using axios without any transformations (ie: line-feed conversions)
    b. How to get the snapshot from a camera that is set up for Basic Auth
    c. Base64 encode the raw data using Nodejs Buffer class
    d. Write the data to a file, for testing purposes

Remember, this is only a Gist and is not the fully completed code that I use.

https://gist.github.com/hawkeye64/a30e43c8301626f7687b985b5e7b04bd

**Comment by hawkeye64** [comment]
If it helps, I have an updated gist using request as axios would not work with Digest Realm of an Axis camera.

https://gist.github.com/hawkeye64/e67cb5aae8f46d9c94ea2c9a4bb9247b

Someone should close this issue. @chriswiggins ?

**Comment by chriswiggins** [comment]
We should probably include a method to return the image as a Buffer into the code. How would you feel about that @hawkeye64?

**Comment by hawkeye64** [comment]
There is now an onvif-snapshot package. Found here: https://github.com/chriswiggins/onvif-snapshot
As soon as @chriswiggins takes the latest PR, you should be able use it with node (currently snapshot.js library path is incorrect in package.json).

I have a sample app based on onvif and onvif-snapshot that I'll be releasing soon.

**Comment by chriswiggins** [comment]
I'll close this, we have the package up and running :-)

Thanks for the help @hawkeye64 !

**Comment by bbruno51** [comment]
Long time passed, I know, but I think this is useful. In some cases, when trying to get URIs from a remote camera, it returns an URI based on its local IP. In my case, after broke my mind a big bit, I discovered this. The solution is based on replace local IP with standard remote IP with a few lines of code.

```
// Function to search for index of nth occurrences
function getPosition(string, subString, index) {
   return string.split(subString, index).join(subString).length;
}

this.getSnapshotUri({stream:'RTP-Multicast', protocol:'RTSP'}, function(err, stream) {
	// these first three lines do the fix
	let urii = stream.uri;
	let ibar = getPosition(urii, '/', 3);
	let fixedURI = 'http://' + HOST + ':' + PORT + urii.substring(ibar);
	request({
		method: 'GET',
		uri: fixedURI,
		...
```
