### ISSUE TITLE
Problem with discovery when a lan printer is in the network

### ISSUE THREAD

**Issue by francesco-ismb** [agsh/onvif#78]
Hi,

I noticed that if some device, in my case a LAN printer, respond to a discovery request, the library doesn't check if that response message is onvif compliant. Then the library raise an exception when it try to create the cam object. I think it's enough adding a check here : https://github.com/agsh/onvif/blob/5cfed69389c5ba3eeef2a411f3ae1caf33119172/lib/discovery.js#L101

**Comment by RogerHardiman** [comment]
Hi @francesco-ismb 
Do you still have your LAN printer?
i am interested in getting more details on the exception that is raised

**Comment by chriswiggins** [comment]
Closing out old issue
