### ISSUE TITLE
Can't play x-vlc format...

### ISSUE THREAD

**Issue by stakutis** [agsh/onvif#79]
Browsers don't seem to like that format now and it seems support has been removed from Chrome/others.

I can use the API to display a single image but I want to display live video/stream. How do I encode the html with that URI?

**Comment by agsh** [comment]
Sure, you can use different solutions like Flussonic or Kurento.
Or maybe https://github.com/mpromonet/webrtc-streamer or https://github.com/agsh/rtsp-ffmpeg

**Comment by stakutis** [comment]
Oh, ok, i think.  My goal is just to display live video in a web page.  The
sample/examples dont work because of the vlc thing.  I dont want to set up
a video server to do some xlate/buffering.  Ideas?


Chris Stakutis
978 764 3488
http://www.concordsoftwareandexecutiveconsulting.com/

**Comment by hawkeye64** [comment]
@stakutis Not sure if you've solved your situation yet. I have just added a getSnapshot() function into the media.js file which may help you. You can find the PR here: https://github.com/agsh/onvif/pull/81

**Comment by KDWangBoss** [comment]
请问要怎么使用它呢？api里面写的是getSnapshotUri不是getSnapshot

**Comment by Venryx** [comment]
I can confirm that using `rtsp-ffmpeg` works fine for playback in the browser.

My program is in electron, so I just read the frame data returned by rtsp-ffmpeg, and send it to the frontend Javascript, as shown in the sample: https://github.com/agsh/rtsp-ffmpeg#sample

**Comment by chriswiggins** [comment]
Closing out old issue
