### ISSUE TITLE
Something wrong with get profiletoken

### ISSUE THREAD

**Issue by EastL** [agsh/onvif#8]
Hello~I'm now using your onvif on my project, and I would like to discuss some questions with you.

I use your getStreamUri function but sometimes it got this error:

/home/Hydra/node_modules/onvif/lib/media.js:219
'<ProfileToken>' + (options.profileToken || this.activeSource.profileToken)
^
TypeError: Cannot read property 'profileToken' of undefined
at Cam.getStreamUri (/home/Hydra/node_modules/onvif/lib/media.js:219:65)
at null.<anonymous> (/home/Hydra/lib/wrapper/devices/onvifc.js:143:16)
at null.<anonymous> (/home/Hydra/node_modules/onvif/lib/cam.js:473:13)
at ClientRequest.<anonymous> (/home/Hydra/node_modules/onvif/lib/cam.js:172:3)
at ClientRequest.EventEmitter.emit (events.js:95:17)
at Socket.socketOnData (http.js:1588:9)
at TCP.onread (net.js:525:27) 

When it runs on the same camera, sometimes success, sometimes error, And when this error occurs, camera still respone getProfiles correctly. How can I fix this problem, please give me advice, thanks.

**Comment by agsh** [comment]
Do you run this method after `connect` camera method or after a `connect`event? Can I look at the sourcecode?
Method which defines `this.activeSource.profileToken` here: https://github.com/agsh/onvif/blob/master/lib/cam.js#L362 and it executes once here: https://github.com/agsh/onvif/blob/master/lib/cam.js#L109

**Comment by EastL** [comment]
My sourcecode executes getStreamUri here:
https://github.com/imonology/Hydra-Wrapper/blob/master/devices/onvifc.js#L143

**Comment by mchen6** [comment]
I once had this random error too, but now it works fine after I ensure getStreamUri() is invoked after cam.connect() is done.

**Comment by EastL** [comment]
@mchen6  Can you give some example how to use cam.connect() before getStreamUri ?

**Comment by mchen6** [comment]
Below is a rough example.

var http = require('http');
var onvif = require('onvif');
var Cam = onvif.Cam;
var camera = [];
var discovered = false;

function discover() {
  onvif.Discovery.probe(function(err, cams) {
    if(err) { throw err; }

    var i = 0;

    cams.forEach(function(cam) {
      cam.username = 'admin';
      cam.password = '1234';
      cam.connect();
      cam.getDeviceInformation(function(err, info, xml) {
        if (err) { throw err; }
        console.log("Camera info:   " + JSON.stringify(info));

        var options = {};
        options.hostname = cam.hostname;
        options.username = cam.username;
        options.password = cam.password;
        options.port = cam.port;

        camera[i] = new Cam(options, function(err) {
          if (err) { throw err; }
        });
        i++;
        discovered = true;
      });
    });
  });
}

function Usage(){
  console.log("Command line:\ndiscover\ngetstream\nmove <X> <Y> <Z>\n");
}

function getStreamAddr() {
  if (discovered == false) {
    console.log("No camera has been found yet, run discover command first");
  }
  for (var i in camera) {
    camera[i].getStreamUri({protocol:'RTSP'}, function(err, stream) {
      console.log("Video stream address:   " + stream.uri);
    });
  }
}

function move(x_axis, y_axis, zoom) {
  if (discovered == false) {
    console.log("No camera has been found yet, run discover command first");
    return;
  }
  var options = {};
  options.x = x_axis;
  options.y = y_axis;
  options.z = zoom;
  options.profileToken = '';
  camera[0].absoluteMove(options);
}

Usage();

var stdin = process.openStdin();
stdin.on('data', function(chunk) {

    if(chunk.toString() == 'x\n') process.exit(0);
    else if(chunk.toString() == 'discover\n') discover();
    else if(chunk.toString() == 'getstream\n') getStreamAddr();
    else {
      var cmd = chunk.toString().split(" ");
      if (cmd[0] != "move") {
        Usage();
        return;
      }
      var x = cmd[1]; var y = cmd[2]; var z = cmd[3];
      move(x, y, z);
    }
});

**Comment by BlueT** [comment]
@mchen6 :+1:

**Comment by EastL** [comment]
Um........ I call the cam.connect and got this error...

/home/Hydra/node_modules/onvif/lib/cam.js:96
			callback.call(this, err);
			         ^
TypeError: Cannot call method 'call' of undefined
    at null.<anonymous> (/home/gkb/Hydra/node_modules/onvif/lib/cam.js:96:13)
    at null.<anonymous> (/home/gkb/Hydra/node_modules/onvif/lib/cam.js:322:13)
    at ClientRequest.<anonymous> (/home/gkb/Hydra/node_modules/onvif/lib/cam.js:172:3)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketOnData (http.js:1588:9)
    at TCP.onread (net.js:525:27)

**Comment by agsh** [comment]
I've seen the code. First point is that you don't handle errors. And it is a very important.
There are two way of connecting to the camera:
First - you specifying all arguments, including `username` and `password`, then constructor immediately starts `connect` method.
Second - you skip `username` and `password` and can call `connect` later manually.
In the both cases you should pay attention on `err` argument in all callback functions.
For me it seems that you have no access (wrong username and password) to the camera. So you can run the most of the device methods, but result in first callback's argument allways will be the same "[Error: ONVIF SOAP Fault: Sender not authorized]" . And some more methods crashes cause you haven't got several tokens which are requested in the connection phase because you also haven't got access. 
Try add this lines in your code and look what will happen:
```js
this.getDeviceInformation(function(err, stream){
  if (err) {console.log('getDeviceInformation error'); throw err;}
     var Uri_stream;
     var cam_this = this;
      cam_this.getStreamUri(function(err, uri){
         if (err) {console.log('getStreamUri error'); throw err;}
         Uri_stream = uri;
```
Another possibility this error is strict SOAP authorization. Here my TODO about it: https://github.com/agsh/onvif/blob/master/lib/cam.js#L509 So if everything with your authorization is fine, write me and I'll check this out.

Question for all: How do you think, should I add a compulsory check for camera authorization it each method?

**Comment by EastL** [comment]
@agsh  Thanks a lot ! But now here are some problems with my environment.... I'll check it soon and response the question.

**Comment by EastL** [comment]
I run the same method and got the random error..... Here are the success
and fail result

gkb@gkb:~/Hydra/lib/wrapper/test/onvif$ node getDeviceInformation.js
this.__proto__
{}
initiating: ip-192.168.0.146 port-80 username-admin password-admn
{ manufacturer: 'VIVOTEK',
  model: 'FE8181V',
  firmwareVersion: 'FE8181-VVTK-0100',
  serialNumber: '0002D130A379',
  hardwareId: 'TI' }
onDone
{ Model: 'FE8181V',
  Serial: '0002D130A379',
  Version: 'FE8181-VVTK-0100',
  rtsp: 'rtsp://192.168.0.146/live.sdp' }
{ manufacturer: 'VIVOTEK',
  model: 'FE8181V',
  firmwareVersion: 'FE8181-VVTK-0100',
  serialNumber: '0002D130A379',
  hardwareId: 'TI' }
onDone
{ Model: 'FE8181V',
  Serial: '0002D130A379',
  Version: 'FE8181-VVTK-0100',
  rtsp: 'rtsp://192.168.0.146/live.sdp' }


gkb@gkb:~/Hydra/lib/wrapper/test/onvif$ node getDeviceInformation.js
this.__proto__
{}
initiating: ip-192.168.0.146 port-80 username-admin password-admn
getDeviceInformation error

/home/gkb/Hydra/lib/wrapper/devices/onvifc.js:144
if (err) {console.log('getDeviceInformation error'); throw err;}

             ^
Error: Parse Error
    at Socket.socketOnData (http.js:1583:20)
    at TCP.onread (net.js:525:27)


I think the camera authorization is my problem, if you can add the check
that is great for who is new on onvif like me....... and the "strict SOAP
authorization" I don't get it....


Sorry I can't connect the github so I send mail....

2015-06-03 22:35 GMT+08:00 Andrew Laptev <notifications@github.com>:

**Comment by agsh** [comment]
Sorry, but I think that this is a hardware problem of your camera. Just look at this error discussion here: https://github.com/joyent/node/issues/4863#issuecomment-33853119
To ensure in this, please add some marker here https://github.com/agsh/onvif/blob/master/lib/cam.js#L174 like this:
```js
req.on('error', function(err) {
    console.log('Request error!');
    callback(err);
});
```
And rerun your test. As said in documentation to node.js `If any error is encountered during the request (be that with DNS resolution, TCP level errors, or actual HTTP parse errors) an 'error' event is emitted on the returned request object.`
I'll be waiting for your answer to think about workaroud.

Also I'll add authorization check in the future releases, thanks!

**Comment by agsh** [comment]
@mchen6 Also, as I understand your code
```js
function discover() {
  onvif.Discovery.probe(function(err, cams) {
    if(err) { throw err; }

    var i = 0;

    cams.forEach(function(cam) {
      cam.username = 'admin';
      cam.password = '1234';
      cam.connect();
      cam.getDeviceInformation(function(err, info, xml) {
        if (err) { throw err; }
        console.log("Camera info:   " + JSON.stringify(info));

        var options = {};
        options.hostname = cam.hostname;
        options.username = cam.username;
        options.password = cam.password;
        options.port = cam.port;

        camera[i] = new Cam(options, function(err) {
          if (err) { throw err; }
        });
        i++;
        discovered = true;
      });
    });
  });
}
```
You can simplify it just like this, because discovered cams are real cams, just not connected as it written in docs:
```js
function discover() {
  onvif.Discovery.probe(function(err, cams) {
    if(err) { throw err; }
    cams.forEach(function(cam) {
      cam.username = 'admin';
      cam.password = '1234';
      cam.connect(function(err) {
        if (err) { throw err; }
        cam.getDeviceInformation(function(err, info, xml) {
          if (err) { throw err; }
          console.log("Camera info:   " + JSON.stringify(info));    
          camera.push(cam);
          discovered = true;
        });
      });
    });
  });
}
```

**Comment by mchen6** [comment]
Thanks!

IMHO it could be useful to document it said only after connect() is done the cam object is fully initialized. Since random error may occur if further calls are made outside connect's callback.

Thanks
Miaobo

�� 2015��6��5����05:37��Andrew Laptev <notifications@github.com<mailto:notifications@github.com>> ������


@mchen6<https://github.com/mchen6> Also, as I understand your code

function discover() {
  onvif.Discovery.probe(function(err, cams) {
    if(err) { throw err; }

    var i = 0;

    cams.forEach(function(cam) {
      cam.username = 'admin';
      cam.password = '1234';
      cam.connect();
      cam.getDeviceInformation(function(err, info, xml) {
        if (err) { throw err; }
        console.log("Camera info:   " + JSON.stringify(info));

        var options = {};
        options.hostname = cam.hostname;
        options.username = cam.username;
        options.password = cam.password;
        options.port = cam.port;

        camera[i] = new Cam(options, function(err) {
          if (err) { throw err; }
        });
        i++;
        discovered = true;
      });
    });
  });
}

You can simplify it just like this, because discovered cams are real cams, just not connected as it written in docs:

function discover() {
  onvif.Discovery.probe(function(err, cams) {
    if(err) { throw err; }
    cams.forEach(function(cam) {
      cam.username = 'admin';
      cam.password = '1234';
      cam.connect(function(err) {
        if (err) { throw err; }
        cam.getDeviceInformation(function(err, info, xml) {
          if (err) { throw err; }
          console.log("Camera info:   " + JSON.stringify(info));
          camera.push(cam);
          discovered = true;
        });
      });
    });
  });
}

��

**Comment by EastL** [comment]
@agsh This is the message
gkb@gkb:~/Hydra/lib/wrapper/test/onvif$ node getDeviceInformation.js 
this.__proto__
{}
Request error!
Request error!
Request error!
Request error!
initiating: ip-192.168.0.146 port-80 username-admin password-admn 
getDeviceInformation error
/home/gkb/Hydra/lib/wrapper/devices/onvifc.js:144
if (err) {console.log('getDeviceInformation error'); throw err;}
^
Error: Parse Error
at Socket.socketOnData (http.js:1583:20)
at TCP.onread (net.js:525:27)

It prints 'Request error!' random times,  "a software problem of your camera", I want to know the problem which do you think, thanks.

**Comment by agsh** [comment]
@mchen6 Ok, I'll do this, thanks. By the way, there is also `connect` event which can help you.
```js
var cam = new Cam({...});
cam.on('connect', function(err) {
  // do everything with your cam
});
```

**Comment by agsh** [comment]
@EastL This means that your camera sends wrong HTML responses which are non-standart. You can check it by Wireshark for example.
The solution is to refuse http nodejs module and parse raw tcp responses.
But it is very hard, better you should buy another camera more ONVIF-compliant.

**Comment by EastL** [comment]
But why sometimes it works sucessfully ?

**Comment by agsh** [comment]
Hardware problems, or network problems, I don't know. Please check packet sending via Wireshark to ensure.

**Comment by EastL** [comment]
OK, thanks, but I can't connect the camera now, I'll check the packet on Monday.

**Comment by EastL** [comment]
Hello~this is the response of GetDeviceInformation of IPCam:
HTTP/1.1 200 OK
Content-Type: application/soap+xml; charset=utf-8
Content-Length: 877

<?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:xs="http://www.w3.org/2000/10/XMLSchema" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"><env:Header><wsa:Action>http://www.onvif.org/ver10/device/wsdl/GetDeviceInformation</wsa:Action></env:Header><env:Body><tds:GetDeviceInformationResponse><tds:Manufacturer>VIVOTEK</tds:Manufacturer><tds:Model>FE8181V</tds:Model><tds:FirmwareVersion>FE8181-VVTK-0100</tds:FirmwareVersion><tds:SerialNumber>0002D130A379</tds:SerialNumber><tds:HardwareId>TI</tds:HardwareId></tds:GetDeviceInformationResponse></env:Body></env:Envelope>

I can't see the problem .....

**Comment by EastL** [comment]
HTTP/1.1 200 OK
Content-Type: application/soap+xml; charset=utf-8
Content-Length: 877

<?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:xs="http://www.w3.org/2000/10/XMLSchema" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"><env:Header><wsa:Action>http://www.onvif.org/ver10/device/wsdl/GetDeviceInformation</wsa:Action></env:Header><env:Body><tds:GetDeviceInformationResponse><tds:Manufacturer>VIVOTEK</tds:Manufacturer><tds:Model>FE8181V</tds:Model><tds:FirmwareVersion>FE8181-VVTK-0100</tds:FirmwareVersion><tds:SerialNumber>0002D130A379</tds:SerialNumber><tds:HardwareId>TI</tds:HardwareId></tds:GetDeviceInformationResponse></env:Body></env:Envelope>

**Comment by agsh** [comment]
1. Ensure that you parse your snippets in markdown style: https://guides.github.com/features/mastering-markdown/
2. Is this the response when error happens?
3. Check the correctness of the Content-Length header

**Comment by EastL** [comment]
I have answered in mail.

**Comment by EastL** [comment]
I think I have finded the problem....
when I remove the http: 
https://github.com/imonology/Hydra-Wrapper/blob/master/devices/onvifc.js#L131

the error will not happen, why............
I added this line is for check the device is exist or not.

**Comment by agsh** [comment]
This is very strange, I still suggest you to check a cam's messaging with network protocol analyzer.
