### ISSUE TITLE
onvif package from npm is missing functionality (0.5.3)

### ISSUE THREAD

**Issue by hawkeye64** [agsh/onvif#80]
npm is reporting the latest onvif package as 0.5.3, but it's missing some functionality, like setPreset and removePreset functions in ptz.js. Anyone know why this is happening? The latest version online on github shows *"version": "0.5.3"*. Is it possible that the version wasn't bumped in the last submission to npm?
I'm going to have to download the latest and use it locally. :(

**Comment by chriswiggins** [comment]
Jeff,

You can use git repositories directly with npm. I’m not sure about the version bump but try this:

npm install git+https://github.com/agsh/onvif

Let me know how you get on

On 23/12/2017, at 5:51 AM, Jeff Galbraith <notifications@github.com<mailto:notifications@github.com>> wrote:


npm is reporting the latest onvif package as 0.5.3, but it's missing some functionality, like setPreset and removePreset functions in ptz.js. Anyone know why this is happening? The latest version online on github shows "version": "0.5.3". Is it possible that the version wasn't bumped in the last submission to npm?
I'm going to have to download the latest and use it locally. :(

**Comment by agsh** [comment]
Hi @hawkeye64 
Also, hello to @chriswiggins, thank you a lot!
Sorry for the late releases, nowdays I'm off cameras work. Maybe in the nearest months, I'll rewrite this with async/await.
Are you sure that the current version on github is stable? If so, I can publish it with 0.5.4 tag.

**Comment by hawkeye64** [comment]
@chriswiggins I am aware that you can pull directly from github. However, we don't want our build server to  have a requirement of a github account to do so.

@agsh Yes, I verified with npm that 0.5.3 is that latest on npm and it does not have the setPreset and removePreset functionality. If you wouldn't mind bumping it to 0.5.4 and add the missing functionality also do your docs, that would be great! Let me know when you submit and I can test.

**Comment by agsh** [comment]
@hawkeye64 Done!

**Comment by hawkeye64** [comment]
@agsh I created a new project, *npm init*, then *npm install --save onvif* and the package came out 0.5.4 with the setPreset and removePreset functionality. Thanks!
