### ISSUE TITLE
misleading information on connect

### ISSUE THREAD

**Issue by fbertone** [agsh/onvif#94]
I find the documentation of 'connect' a bit misleading:
> In all of that cases you've got disconnected cameras because to manage them you need tuple username:password. So, as shown in the examples, you can assign these properties and call connect method to get full functionality. 

> If the username and password are present, camera tries to connect automatically. Otherwise use connect method. Once again, without credentials you can execute only getSystemDateAndTime method.

> Connect to the camera and fill device information properties with getCapabilities, getVideoSources, getProfiles methods

Even if I don't set any credential the device information properties get filled anyways (without calling connect) and I can use most of the methods, not just getSystemDateAndTime as declared.

**Moreover, if I set wrong credentials and call connect I would expect to get an error but I don't get any at all**

**Comment by hawkeye64** [comment]
I've seen this when there is no username/password set on the camera. In this case, whatever you set is just ignored by the camera.
Can you verify?

**Comment by fbertone** [comment]
username and password are set and I have to use them to access things like snapshot and streams, but all (or most) getXXX calls are unauthenticated

**Comment by RogerHardiman** [comment]
The Readme and the code do not match for new Cam() as @fbertone found.
README says
```If the username and password are present, camera tries to connect automatically. Otherwise use connect method. Once again, without credentials you can execute only getSystemDateAndTime method.```

in cam.js is this code is
```
	setImmediate(function() {
		this.connect(callback);
	}.bind(this));
```

To match the README it should say
```
	setImmediate(function() {
		if (username && password) this.connect(callback);
	}.bind(this));
```

I will change the README to match the code

**Comment by RogerHardiman** [comment]
Have updated the README in bbdec568fbda1c84a421c0eab1cb7610f237bfee

Also a bad username and password will return `err.message` of
ONVIF SOAP Fault: Sender not authorizedThe action requested requires authorization and the sender is not authorized
