### ISSUE TITLE
Find IP address of IP camera in network

### ISSUE THREAD

**Issue by komalpharate** [agsh/onvif#98]
I have Sricam SP007
Want to find its IP address
Can I use this module to do that?
And How?
The onvif.Discovery can be used?

**Comment by agsh** [comment]
Yes, you can if your camera is in the same network. Just call the `discovery` method and look at the answer.

**Comment by komalpharate** [comment]
Hey,
It worked.
Thanks a lot!

**Comment by komalpharate** [comment]
Hi,
Can I get macAddress of the camera?

**Comment by agsh** [comment]
With `getNetworkInterfaces` method
https://github.com/agsh/onvif/blob/master/lib/device.js#L78

**Comment by agsh** [comment]
Something like this:
```js
new Cam({
  hostname: <CAMERA_HOST>,
  username: <USERNAME>,
  password: <PASSWORD>
}, function(err) {
  this.getNetworkInterfaces((err, nI) => {
    console.log(nI.info.hwAddress);
  });
});
```

**Comment by komalpharate** [comment]
`onvif.Discovery.probe(function(err, cams) {
// function will be called only after timeout (5 sec by default)
    if (err) { throw err; }
    
     cams.forEach(function(cam) {
       	cam.getNetworkInterfaces((err, nI) => {
    	console.log(nI.info.hwAddress);
        });
     });
});

This isnt working..

`

**Comment by komalpharate** [comment]
`onvif.Discovery.on('device', function(cam,rinfo,xml){
    // function will be called as soon as NVT responses
    console.log('Reply from ' + rinfo.address);
    console.log(cam.hostname + ':' + cam.port + cam.path);
    cam.getNetworkInterfaces((err, nI) => {
    console.log(nI.info.hwAddress);
  });
	
})
onvif.Discovery.probe();`
Also
This isnt working

**Comment by komalpharate** [comment]
My camera doesnt require username and password
