### ISSUE TITLE
What this timeout signifies in Discovery.probe(options)?

### ISSUE THREAD

**Issue by komalpharate** [agsh/onvif#99]
Discovery.probe(options, callback)

Options

    timeout, number. Time the probe method will wait NVT responses in ms

**Comment by RogerHardiman** [comment]
When using discovery, the ONVIF library will send out a broadcast packet and wait for Cameras (NVTs/Network Video Transmitters) to send their reply messages.
The timeout is in milliseconds. It tells the ONVIF library how long to wait for replies.
So as an example if options was set to {timeout:10000} then the ONVIF Library will send the broadcast discovery message and then listen for 10 seconds for any replies. After 10 seconds it stops listening for replies.

... tested by adding {timeout:10000} to the options in example4.js
